### ISSUE TITLE
Errors while compiling

### ISSUE THREAD

**Issue by energo5** [romikavinda/People-Tracking-with-OpenCV-#1]
Hi, can you help with this errors when compiling you project in Visual Studio 2017:
1>------ Build started: Project: people_tracking, Configuration: Release x64 ------
1> Creating library D:\OpenCV\VS\people_tracking\x64\Release\people_tracking.lib and object D:\OpenCV\VS\people_tracking\x64\Release\people_tracking.exp
1>people_tracking.obj : error LNK2001: unresolved external symbol "public: __cdecl TKalmanFilter::TKalmanFilter(class cv::Point_<float>,float,float)" (??0TKalmanFilter@@QEAA@V?$Point_@M@cv@@MM@Z)
1>people_tracking.obj : error LNK2001: unresolved external symbol "public: __cdecl TKalmanFilter::~TKalmanFilter(void)" (??1TKalmanFilter@@QEAA@XZ)
1>people_tracking.obj : error LNK2001: unresolved external symbol "public: __cdecl AssignmentProblemSolver::AssignmentProblemSolver(void)" (??0AssignmentProblemSolver@@QEAA@XZ)
1>people_tracking.obj : error LNK2001: unresolved external symbol "public: __cdecl AssignmentProblemSolver::~AssignmentProblemSolver(void)" (??1AssignmentProblemSolver@@QEAA@XZ)
1>people_tracking.obj : error LNK2001: unresolved external symbol "public: double __cdecl AssignmentProblemSolver::Solve(class std::vector<class std::vector<double,class std::allocator<double> >,class std::allocator<class std::vector<double,class std::allocator<double> > > > &,class std::vector<int,class std::allocator<int> > &,enum AssignmentProblemSolver::TMethod)" (?Solve@AssignmentProblemSolver@@QEAANAEAV?$vector@V?$vector@NV?$allocator@N@std@@@std@@V?$allocator@V?$vector@NV?$allocator@N@std@@@std@@@2@@std@@AEAV?$vector@HV?$allocator@H@std@@@3@W4TMethod@1@@Z)
1>people_tracking.obj : error LNK2001: unresolved external symbol "public: class cv::Point_<float> __cdecl TKalmanFilter::GetPrediction(void)" (?GetPrediction@TKalmanFilter@@QEAA?AV?$Point_@M@cv@@XZ)
1>people_tracking.obj : error LNK2001: unresolved external symbol "public: class cv::Point_<float> __cdecl TKalmanFilter::Update(class cv::Point_<float>,bool)" (?Update@TKalmanFilter@@QEAA?AV?$Point_@M@cv@@V23@_N@Z)
1>D:\OpenCV\VS\people_tracking\x64\Release\people_tracking.exe : fatal error LNK1120: 7 unresolved externals
1>Done building project "people_tracking.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by romikavinda** [comment]
Hi,
It seems like the linker is unable to locate the header files in your project ,  try linking them and compile.
Configuration Properties" --> "C/C++“ --> "General" --> "Additional Include Directories and point to the header files in the project.

**Comment by energo5** [comment]
Hi.
Unfortunately, this procedure did not help.

Eugene

**Comment by romikavinda** [comment]
The Log indicates that the compiler is unable to figure out some classes. The mentioned classes are coded in the header files. Maybe try creating a fresh project and clean build?

**Comment by energo5** [comment]
I initially did your project from scratch, only your code from github and nothing else.

**Comment by romikavinda** [comment]
Try using the https://github.com/Smorodov/Multitarget-tracker project and link the main.cpp from this project and do the necessary code changes and check.

**Comment by energo5** [comment]
Thanks. I'll take a look.
